### ISSUE TITLE
download from huggingface failed

### ISSUE THREAD

**Issue by DaBaiTuu** [DLYuanGod/TinyGPT-V#12]
Can you provide another way to download the checkpoint?
Maybe modelscope?
抱脸是真上不去，谢谢

**Comment by DLYuanGod** [comment]
你好

我们已经加急将模型的Stage3文件上传到Modelscope社区以方便国内用户下载:
https://modelscope.cn/models/LC2023/TinyGPT-V/file/view/master/TinyGPT-V_for_Stage3.pth

其余的各部分下载，我们正在逐步完善，包括中文的markdown文件，请您持续关注谢谢！

Hi!

We have uploaded the Stage3 file of the model to the Modelscope community as soon as possible to facilitate the download of the model for our users in China.
https://modelscope.cn/models/LC2023/TinyGPT-V/file/view/master/TinyGPT-V_for_Stage3.pth

We are gradually improving the rest of the downloads, including the Chinese markdown files, so please stay tuned!

**Comment by DaBaiTuu** [comment]
> 你好
> 
> 我们已经加急将模型的Stage3文件上传到Modelscope社区以方便国内用户下载: https://modelscope.cn/models/LC2023/TinyGPT-V/file/view/master/TinyGPT-V_for_Stage3.pth
> 
> 其余的各部分下载，我们正在逐步完善，包括中文的markdown文件，请您持续关注谢谢！
> 
> Hi!
> 
> We have uploaded the Stage3 file of the model to the Modelscope community as soon as possible to facilitate the download of the model for our users in China. https://modelscope.cn/models/LC2023/TinyGPT-V/file/view/master/TinyGPT-V_for_Stage3.pth
> 
> We are gradually improving the rest of the downloads, including the Chinese markdown files, so please stay tuned!

多谢，期待你们的更新和完善以及中文的文档

**Comment by DaBaiTuu** [comment]
顺便问下，跑推理只需要这一个pth就够了么，还是还需要 phi2 的 pth

**Comment by DLYuanGod** [comment]
是需要Phi-2的pth的，转载此模型有些复杂，我得申请许可才能添加进入Modelscope社区。

It's the Phi-2 pth that's needed to reproduce this model is a bit complicated and I'll have to apply for permission to add it to the Modelscope community.

**Comment by DaBaiTuu** [comment]
> 是需要Phi-2的pth的，转载此模型有些复杂，我得申请许可才能添加进入Modelscope社区。
> 
> It's the Phi-2 pth that's needed to reproduce this model is a bit complicated and I'll have to apply for permission to add it to the Modelscope community.

好的好的多谢，还麻烦可以的话，在Readme里把inference部分再完善些就好了。
