### ISSUE TITLE
performance evaluation details

### ISSUE THREAD

**Issue by dylanqyuan** [DLYuanGod/TinyGPT-V#15]
Nice work!
Have you ever do some experiments about the difference performances  among stage 1, 2, and 3 ? :laugh:

**Comment by DLYuanGod** [comment]
Hello. 
Yes, we tested his performance at every checkpoints.
The performance of stage 1 and stage 2 is very poor because it is only the pre-training part.
Stage 3 performs slightly worse than stage 4, which we will put in the next version of the paper.
