### ISSUE TITLE
Size mismatch for stage1 checkpoints

### ISSUE THREAD

**Issue by wangskyone** [DLYuanGod/TinyGPT-V#22]
![image](https://github.com/DLYuanGod/TinyGPT-V/assets/50222939/7205b177-b1cf-461e-bd44-42e03c1b81f8)

**Comment by llizhaoxu** [comment]
Hi 

Thanks for your interest. In demo_v2, your should use Stage4.pth instead of Stage1.pth cause the input training image have different size, and the model input is a little bit different. ( Note: the stage4 is a test version)
