### ISSUE TITLE
On the  stage 4，the Q-Former is trained, however   the Q-Former  should not been trained  in  the paper 

### ISSUE THREAD

**Issue by TangYuan96** [DLYuanGod/TinyGPT-V#23]
the freeze  is false, https://github.com/DLYuanGod/TinyGPT-V/blob/12b036a34090fb1f06d81f25c388b13db4c21fe3/minigpt4/models/minigpt_v2.py#L68

**Comment by llizhaoxu** [comment]
Hi 

Thanks for your reminder. Stage 4 is actually a test version. In the version we will release in the future, the Q-Former is not trained.

**Comment by TangYuan96** [comment]
Thanks for your reply. I get it.
