### ISSUE TITLE
Unable to run on a remote jupyter environment

### ISSUE THREAD

**Issue by twilwa** [DLYuanGod/TinyGPT-V#4]
**Describe the bug**
see title

**To Reproduce**
conda env create -f environment.yml

**Expected behavior**

conda installation to complete succesfully

**Screenshots**

![image](https://github.com/DLYuanGod/TinyGPT-V/assets/111034762/b39260cb-d22a-4834-8fcf-babb960c2d29)

**Desktop (please complete the following information):**
Ubuntu 22.04, remote VM

**Additional context**
I haven't attempted to reproduce locally -- when i was googling for that 4.37dev version I couldn't find it on conda-forge

**Comment by DLYuanGod** [comment]
Oh, I'm sorry.
conda may have problems installing the latest version of the transformers library
I have updated my environment.yml file now you can put this updated repository
Reinstall the environment by executing the following code:

conda remove --name tinygptv --all
conda env create -f environment.yml

**Comment by twilwa** [comment]
we're in business! ty for the speedy reply
