### ISSUE TITLE
'PhiAttention' object has no attribute 'q_layernorm'/ 'k_layernorm'/ 'k_postnorm'

### ISSUE THREAD

**Issue by zr-icu** [DLYuanGod/TinyGPT-V#5]
Thanks for your excellent job!! 
I want to train my own dataset from the scratch, however, when I load the model from phi. It raises a problem that **'PhiAttention' object has no attribute 'q_layernorm'**  . I check the config.py in phi model directory. I found that the qk_layernorm is set as False. So I change it into True. But I still get the error that **'PhiDecoderLayer' object has no attribute 'post_layernorm'** Could you help to solve it?  
Thank you very much !

**Comment by DLYuanGod** [comment]
Hello! Thank you for your interest in this work.

Please check section 4 of Getting Started in the README.md file !

Or just replace TinyGPT-V/modeling_phi.py with model/phi/modeling_phi.py in the transformers library.

**Comment by zr-icu** [comment]
Oh!!  My bad. I am sorry for my careless～  I thought It will work when doing inference. So I missed that step~ The problem is solved. Cheers!
